name: CI
on:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled
    branches:
      - master

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build:
    name: Build Test and Publish
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      GITHUB_TOKEN: ${{ secrets.KONGPONENTS_BOT_PAT }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN_PUBLIC_PUBLISH }}

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup PNPM with Dependencies
        uses: ./.github/actions/setup-node-with-dependencies/
        with:
          force-install: true


      - name: Lint
        run: yarn run lint

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn run test

      - name: Prepare Publish
        if: ${{ github.event_name == 'push' }}
        run: |
          git config --global user.name 'kongponents-bot'
          git config --global user.email '95302551+kongponents-bot@users.noreply.github.com'
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc

      - name: Semantic Release
        if: ${{ github.event_name == 'push' }}
        uses: cycjimmy/semantic-release-action@v4
